# Sample Lando config for use with this image
name: lando-wp-theme
recipe: wordpress

services:
  appserver:
    type: php:custom

    overrides:
      services:
        image: sitecrafting/lando-wp-theme
        environment:
          LANDO_WEBROOT: /var/www/html
          # specify defaults to setup-wordpress.bash
          DEFAULT_URL: 'https://lando-wp-theme.lndo.site'
          DEFAULT_TITLE: 'My Beautiful Site'
          DEFAULT_ADMIN_USER: 'admin'
          DEFAULT_ADMIN_PASSWORD: 'password'
          DEFAULT_ADMIN_EMAIL: 'admin@example.com'

tooling:
  install:
    service: appserver
    cmd: setup-wordpress.bash
    description: 'Install and configure WordPress for custom theme dev'

  w:
    service: appserver
    cmd: 'wp --path=/var/www/html'
    description: 'Run wp-cli commands within the container webroot'
